### ISSUE TITLE
Pre-Site Release Checklist

### ISSUE THREAD

**Issue by MG10327** [MG10327/Documentation#159]
- [ ] All Assets work on all sizes
- [ ] No text ragging on all sizes (no lines of text that are one word only. Wrap it together or add a line break to put at least two words on one line.)
- [ ] Animations play on all sizes
- [ ] Videos work on all sizes if you use any
- [ ] Voice over works on all screen sizes (Every Apple Device Size) See #161  to see how to use Voice Over on Windows and Mac
- [ ] All images have descriptive aria labels
- [ ] All animations have descriptive aria labels
- [ ] Any elements that aren't described well in voice over are given descriptive aria labels
- [ ] All React test pass
- [ ] The site is responsive for every Apple device size
- [ ] All of the above work in every Apple Device size **on Portrait AND Landscape** Here is my list of Apple Device Media queries #160 
- [ ] The site functions well in `Safari` (highest priority), `Chrome` (second highest priority), and `FireFox` (lowest priority)
